/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AprendaRouteImport } from './routes/aprenda'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CriadoresRouteImport } from './routes/criadores'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AuthCarteirasRouteImport } from './routes/_auth/carteiras'
import { Route as AuthPagamentoRouteImport } from './routes/_auth/pagamento'
import { Route as AuthPerfilRouteImport } from './routes/_auth/perfil'
import { Route as NftsNftIdRouteImport } from './routes/nfts/$nftId'
import { Route as AuthPedidosOrderIdRouteImport } from './routes/_auth/pedidos/$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendaRoute = AprendaRouteImport.update({
  id: '/aprenda',
  path: '/aprenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CriadoresRoute = CriadoresRouteImport.update({
  id: '/criadores',
  path: '/criadores',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCarteirasRoute = AuthCarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPagamentoRoute = AuthPagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPerfilRoute = AuthPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthRoute,
} as any)
const NftsNftIdRoute = NftsNftIdRouteImport.update({
  id: '/nfts/$nftId',
  path: '/nfts/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPedidosOrderIdRoute = AuthPedidosOrderIdRouteImport.update({
  id: '/pedidos/$orderId',
  path: '/pedidos/$orderId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/criadores': typeof CriadoresRoute
  '/entrar': typeof EntrarRoute
  '/carteiras': typeof AuthCarteirasRoute
  '/pagamento': typeof AuthPagamentoRoute
  '/perfil': typeof AuthPerfilRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/pedidos/$orderId': typeof AuthPedidosOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/criadores': typeof CriadoresRoute
  '/entrar': typeof EntrarRoute
  '/carteiras': typeof AuthCarteirasRoute
  '/pagamento': typeof AuthPagamentoRoute
  '/perfil': typeof AuthPerfilRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/pedidos/$orderId': typeof AuthPedidosOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/aprenda': typeof AprendaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/criadores': typeof CriadoresRoute
  '/entrar': typeof EntrarRoute
  '/_auth/carteiras': typeof AuthCarteirasRoute
  '/_auth/pagamento': typeof AuthPagamentoRoute
  '/_auth/perfil': typeof AuthPerfilRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/_auth/pedidos/$orderId': typeof AuthPedidosOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprenda'
    | '/cadastro'
    | '/carrinho'
    | '/criadores'
    | '/entrar'
    | '/carteiras'
    | '/pagamento'
    | '/perfil'
    | '/nfts/$nftId'
    | '/pedidos/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprenda'
    | '/cadastro'
    | '/carrinho'
    | '/criadores'
    | '/entrar'
    | '/carteiras'
    | '/pagamento'
    | '/perfil'
    | '/nfts/$nftId'
    | '/pedidos/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/aprenda'
    | '/cadastro'
    | '/carrinho'
    | '/criadores'
    | '/entrar'
    | '/_auth/carteiras'
    | '/_auth/pagamento'
    | '/_auth/perfil'
    | '/nfts/$nftId'
    | '/_auth/pedidos/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AprendaRoute: typeof AprendaRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CriadoresRoute: typeof CriadoresRoute
  EntrarRoute: typeof EntrarRoute
  NftsNftIdRoute: typeof NftsNftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprenda': {
      id: '/aprenda'
      path: '/aprenda'
      fullPath: '/aprenda'
      preLoaderRoute: typeof AprendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criadores': {
      id: '/criadores'
      path: '/criadores'
      fullPath: '/criadores'
      preLoaderRoute: typeof CriadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/carteiras': {
      id: '/_auth/carteiras'
      path: '/carteiras'
      fullPath: '/carteiras'
      preLoaderRoute: typeof AuthCarteirasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pagamento': {
      id: '/_auth/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof AuthPagamentoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/perfil': {
      id: '/_auth/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthPerfilRouteImport
      parentRoute: typeof AuthRoute
    }
    '/nfts/$nftId': {
      id: '/nfts/$nftId'
      path: '/nfts/$nftId'
      fullPath: '/nfts/$nftId'
      preLoaderRoute: typeof NftsNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/pedidos/$orderId': {
      id: '/_auth/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof AuthPedidosOrderIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCarteirasRoute: typeof AuthCarteirasRoute
  AuthPagamentoRoute: typeof AuthPagamentoRoute
  AuthPerfilRoute: typeof AuthPerfilRoute
  AuthPedidosOrderIdRoute: typeof AuthPedidosOrderIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCarteirasRoute: AuthCarteirasRoute,
  AuthPagamentoRoute: AuthPagamentoRoute,
  AuthPerfilRoute: AuthPerfilRoute,
  AuthPedidosOrderIdRoute: AuthPedidosOrderIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AprendaRoute: AprendaRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  CriadoresRoute: CriadoresRoute,
  EntrarRoute: EntrarRoute,
  NftsNftIdRoute: NftsNftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
